### ISSUE TITLE
Showcase (Collapse/Uncollapse) 

### ISSUE THREAD

**Issue by ttvjamit** [talk2MeGooseman/Stream-Closed-Captioner#19]
On the showcase website, it would be nice to have Collapse/Uncollapse to collapse the Most Stream (Offline) stream, and can always uncollapse it if people need to view it there? Live Stream should not have this as it should always be shown.

Collapse should be simple as clicking the - button to hide/unhide.

**Comment by talk2MeGooseman** [comment]
Great idea! What is your opinion seeing maybe the 10-20 most recent offline streams? It’s probably not worth seeing so many, but it’s cool to know :)

**Comment by ttvjamit** [comment]
That could work as 10-20 most recent offline streams. There are some inactive streamers that are shown so I thought of adding show most recent streams in the last 48 hours should do the job nicely. Just an thought 👍

**Comment by talk2MeGooseman** [comment]
Nice, sound like a good way to narrow things down

**Comment by talk2MeGooseman** [comment]
Done
