### ISSUE TITLE
Adjust box width

### ISSUE THREAD

**Issue by ttvjamit** [talk2MeGooseman/Stream-Closed-Captioner#31]
Adjusting the box width, could do it in fixed width of percentage, or custom adjustment with the width box only (not the height, only width).

Percentage such as 100% as default what is shown right now, drop to 80% width, 60%. Should not excess the captions in the box more than 4 words for example "killer is on me" in nice width of box. Could make sub-menu for percentage width box

**Comment by jmytch** [comment]
Or maybe have those cells usually at bottom right corner like the one from the screenshot then anybody can resize the box as they wish that way rather than the option in the CC menu.
![Capture](https://user-images.githubusercontent.com/45726972/79978410-37fd2100-84e3-11ea-8d45-4b57d423fce8.PNG)
