### ISSUE TITLE
Square Text Box - not working

### ISSUE THREAD

**Issue by jmytch** [talk2MeGooseman/Stream-Closed-Captioner#41]
As the new version of Stream Captioner is out, and the square text box is not working. I clicked another settings such as Large, Small text along with dyslexic font and click Square Text Box it doesn't do the trick. Something has break the Square Text Box

**Comment by talk2MeGooseman** [comment]
Hi thanks for reporting! I found the issues shortly after release and already submitted a new version fixing the bug. Hoping twitch will finish reviewing it by end of day tomorrow. Sorry for the issue.

**Comment by talk2MeGooseman** [comment]
Twitch still approved the new version, hoping it gets approved tomorrow so that this annoying bug goes away.

**Comment by jmytch** [comment]
This has been fixed on Twitch end, thank you :)
