### ISSUE TITLE
Fix line increase/decrease settings for Box Size mode

### ISSUE THREAD

**Issue by talk2MeGooseman** [talk2MeGooseman/Stream-Closed-Captioner#43]

**Comment by jmytch** [comment]
I also noticed this issue too, used to watch only 3 lines of wording. Right now it stops at 5 lines maximum for some reason. Glad you noticed this issue.

**Comment by talk2MeGooseman** [comment]
Yeah keeping an eye out on the bugs, working on another small release to fix it :)

**Comment by talk2MeGooseman** [comment]
Fixes the issue locally, going to submit a build in next day or two to get it in the release pipeline

**Comment by talk2MeGooseman** [comment]
Fix deployed! Added in additional feature. Now your settings will be cached in the browser. So when you refresh it will remember that you choose Box Size and only 3 lines.
