### ISSUE TITLE
Decrease lines bug?

### ISSUE THREAD

**Issue by jmytch** [talk2MeGooseman/Stream-Closed-Captioner#75]
Hi, what happened to the 3 lines? I'm liking the Advanced Settings you got there, you could do that with Increase/Decrease captions lines too would be ideal.  I miss the 3 lines, it could be a bug but not sure. Thought I'd let you know

**Comment by talk2MeGooseman** [comment]
Must be a bug for sure, havent changed anything for couple months. My thought its a bug between the "box" size and horizontal mode. But I will be adding more controls in the advanced setting to say how many you lines you want instead of clicking around. Thanks for the report.

**Comment by talk2MeGooseman** [comment]
Think I narrowed down what the bug is, plan to make a new release by end of the week
