### ISSUE TITLE
Ability to disable and delete transcripts

### ISSUE THREAD

**Issue by potatoqualitee** [talk2MeGooseman/Stream-Closed-Captioner#8]
**Describe the bug**

Thank you for this fantastic feature! I no longer have to take up valuable real-estate to ensure my audience can read what I say 💞

Currently, there is no way to disable transcripts and deleting a single line requires two clicks. I am unsure where the transcripts are stored and who has access. In the event that I accidentally leave my mic on, my conversations are preserved unless I explicitly delete them, line by line.

**To Reproduce**
1. Go to https://stream-cc.gooseman.codes/dashboard
2. Cannot find a place to disable transcripts
3. Cannot find an easy way to delete past transcripts

**Expected behavior**
I would expect the option to disable and delete transcripts.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by talk2MeGooseman** [comment]
Thanks for the feedback, Ill add the ability to disable transcripts on the dashboard in the coming week or so. The transcripts feature as a whole is a "beta" feature so it for sure needs to love for UX and features. But Disabling is an easy enough thing to do :)

**Comment by potatoqualitee** [comment]
thanks so much 👍

**Comment by talk2MeGooseman** [comment]
@potatoqualitee Transcript enable/disable is now officially done/released and off by default for all users. Thanks for the feedback, I plan to give the entire transcripts UI/UX a lot of love in the future so until then I hope this helps <3

**Comment by potatoqualitee** [comment]
Yesss awesome, thank you so much! 🎉
